# Generated by Django 6.0 on 2025-12-21 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('season_id', models.IntegerField(db_index=True, default=1)),
                ('round_id', models.IntegerField(default=0)),
                ('current_round_number', models.IntegerField(default=0)),
                ('next_round_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnityServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('server_ip', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy'), ('not_responding', 'Not Responding'), ('not_initialized', 'Not Initialized')], db_index=True, default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('idle_cpu_usage', models.FloatField(default=0.0)),
                ('idle_ram_usage', models.FloatField(default=0.0)),
                ('max_cpu_usage', models.FloatField(default=0.0)),
                ('max_ram_usage', models.FloatField(default=0.0)),
                ('disk_usage', models.FloatField(default=0.0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('total_assigned_planet', models.IntegerField(default=0)),
                ('total_completed_planet', models.IntegerField(default=0)),
                ('total_failed_planet', models.IntegerField(default=0)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_server', to='game_manager.planet')),
            ],
        ),
        migrations.AddField(
            model_name='planet',
            name='processing_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_planets', to='game_manager.unityserver'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='started', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.planet')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_manager.unityserver')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='game_manage_start_t_2457ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='planet',
            index=models.Index(fields=['next_round_time', 'status'], name='game_manage_next_ro_d0b4ed_idx'),
        ),
    ]
