# Generated by Django 6.0 on 2025-12-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.CharField(db_index=True, help_text='Unique planet identifier', max_length=100, primary_key=True, serialize=False)),
                ('season_id', models.IntegerField(db_index=True, default=1, help_text='Current season')),
                ('round_id', models.IntegerField(default=0, help_text='Current round identifier')),
                ('current_round_number', models.IntegerField(default=0, help_text='Running count of completed rounds')),
                ('next_round_time', models.DateTimeField(db_index=True, help_text='When this planet should next be processed')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='queued', help_text='Current processing state', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, help_text='Timestamp of last successful processing', null=True)),
                ('error_retry_count', models.IntegerField(default=0, help_text='Consecutive error count (reset on success, max 5)')),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
            },
        ),
        migrations.CreateModel(
            name='UnityServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, help_text='Unique identifier assigned by Unity client', max_length=100, unique=True)),
                ('server_ip', models.CharField(db_index=True, help_text='IP address of the Unity server', max_length=100)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy'), ('not_responding', 'Not Responding'), ('not_initialized', 'Not Initialized')], db_index=True, default='offline', help_text='Current operational state', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp of most recent heartbeat', null=True)),
                ('idle_cpu_usage', models.FloatField(default=0.0, help_text='CPU % when idle')),
                ('idle_ram_usage', models.FloatField(default=0.0, help_text='RAM % when idle')),
                ('max_cpu_usage', models.FloatField(default=0.0, help_text='Peak CPU % during jobs')),
                ('max_ram_usage', models.FloatField(default=0.0, help_text='Peak RAM % during jobs')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Current disk utilization %')),
                ('connected_at', models.DateTimeField(auto_now_add=True, help_text='First connection timestamp')),
                ('disconnected_at', models.DateTimeField(blank=True, help_text='Last disconnection timestamp', null=True)),
                ('total_assigned_planet', models.IntegerField(default=0, help_text='Total jobs assigned to this server')),
                ('total_completed_planet', models.IntegerField(default=0, help_text='Total successful completions')),
                ('total_failed_planet', models.IntegerField(default=0, help_text='Total failures/errors')),
                ('current_task', models.ForeignKey(blank=True, help_text='Planet currently being processed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_server', to='game_manager.planet')),
            ],
            options={
                'verbose_name': 'Unity Server',
                'verbose_name_plural': 'Unity Servers',
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='processing_server',
            field=models.ForeignKey(blank=True, help_text='Server currently processing this planet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_planets', to='game_manager.unityserver'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When job was assigned')),
                ('end_time', models.DateTimeField(blank=True, help_text='When job finished', null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='started', help_text='Job outcome', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed', null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Processing time in seconds', null=True)),
                ('planet', models.ForeignKey(help_text='Planet that was processed', on_delete=django.db.models.deletion.CASCADE, to='game_manager.planet')),
                ('server', models.ForeignKey(help_text='Server that processed the job', null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_manager.unityserver')),
            ],
            options={
                'verbose_name': 'Task History',
                'verbose_name_plural': 'Task Histories',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['-start_time'], name='game_manage_start_t_2457ab_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='planet',
            index=models.Index(fields=['next_round_time', 'status'], name='planet_schedule_idx'),
        ),
    ]
