# Generated by Django 6.0 on 2025-12-04 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPlanet',
            fields=[
                ('map_id', models.IntegerField(primary_key=True, serialize=False)),
                ('next_round_time', models.DateTimeField(blank=True, null=True)),
                ('season_id', models.IntegerField(default=1)),
                ('round_id', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='current_players',
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='max_players',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_server', to='game_manager.mapplanet'),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.mapplanet')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_manager.gameserver')),
            ],
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
