# Generated by Django 6.0 on 2025-12-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='error_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
