# Generated by Django 6.0 on 2025-12-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_remove_taskhistory_result_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unityserver',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy'), ('not_responding', 'Not Responding'), ('not_initialized', 'Not Initialized')], db_index=True, default='offline', max_length=20),
        ),
    ]
