# Generated by Django 6.0 on 2025-12-07 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0002_mapplanet_remove_gameserver_channel_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskhistory',
            options={'ordering': ['-start_time']},
        ),
        migrations.RenameField(
            model_name='taskhistory',
            old_name='result',
            new_name='result_data',
        ),
        migrations.AddField(
            model_name='gameserver',
            name='connected_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameserver',
            name='cpu_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gameserver',
            name='player_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameserver',
            name='total_jobs_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mapplanet',
            name='last_processed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mapplanet',
            name='map_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mapplanet',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mapplanet',
            name='processing_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_maps', to='game_manager.gameserver'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('completed', 'Completed'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='server_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='gameserver',
            name='status',
            field=models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy')], db_index=True, default='offline', max_length=20),
        ),
        migrations.AlterField(
            model_name='mapplanet',
            name='map_id',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mapplanet',
            name='next_round_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapplanet',
            name='round_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mapplanet',
            name='season_id',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='mapplanet',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='mapplanet',
            index=models.Index(fields=['next_round_time', 'status'], name='game_manage_next_ro_7b3690_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['-start_time'], name='game_manage_start_t_2457ab_idx'),
        ),
    ]
