# Generated by Django 6.0 on 2025-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_alter_unityserver_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unityserver',
            name='server_ip',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
