# Generated by Django 6.0 on 2025-12-09 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_manager', '0003_alter_taskhistory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('map_id', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False)),
                ('season_id', models.IntegerField(db_index=True, default=1)),
                ('round_id', models.IntegerField(default=0)),
                ('current_round_number', models.IntegerField(default=0)),
                ('next_round_time', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], db_index=True, default='queued', max_length=20)),
                ('last_processed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnityServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('server_ip', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('offline', 'Offline'), ('idle', 'Idle'), ('busy', 'Busy'), ('not_responding', 'Not Responding')], db_index=True, default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('total_assigned_map', models.IntegerField(default=0)),
                ('total_completed_map', models.IntegerField(default=0)),
                ('total_failed_map', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='gameserver',
            name='current_task',
        ),
        migrations.RemoveIndex(
            model_name='mapplanet',
            name='game_manage_next_ro_7b3690_idx',
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_manager.planet'),
        ),
        migrations.AddField(
            model_name='unityserver',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_server', to='game_manager.planet'),
        ),
        migrations.AddField(
            model_name='planet',
            name='processing_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_maps', to='game_manager.unityserver'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_manager.unityserver'),
        ),
        migrations.RemoveField(
            model_name='mapplanet',
            name='processing_server',
        ),
        migrations.AddIndex(
            model_name='planet',
            index=models.Index(fields=['next_round_time', 'status'], name='game_manage_next_ro_d0b4ed_idx'),
        ),
        migrations.DeleteModel(
            name='GameServer',
        ),
        migrations.DeleteModel(
            name='MapPlanet',
        ),
    ]
